var moment = require('moment');

module.exports = [
  {
    user_id: 2,
    chef_id: 3,
    food: 'Fried rice',
    cuisine: 'Chinese',
    description: 'I borrowed this recipe from my college roommate. Quick and easy to make!',
    quantity: 3,
    price: 60.41,
    address: '645 1st Street, Beckley, WV 25801',
    order_date: '2007-07-15 11:15:52.973',
    rating: 5,
    review: 'My kids loved the fried rice!!! Thanks chef Dan!',
    createdAt: moment().format('YYYY-MM-DD HH:mm:ss.SSS Z'),
    updatedAt: moment().format('YYYY-MM-DD HH:mm:ss.SSS Z'),
  },
  {
    user_id: 2,
    chef_id: 1,
    food: 'Chicken pasta',
    cuisine: 'Italian',
    description: 'A secret family recipe, passed down from generations.',
    quantity: 2,
    price: 46.82,
    address: '376 Virginia Street, Buffalo, NY 14215',
    order_date: '2013-09-22 01:48:40.745',
    rating: 1,
    review: 'Meh, I\'ve had better.',
    createdAt: moment().format('YYYY-MM-DD HH:mm:ss.SSS Z'),
    updatedAt: moment().format('YYYY-MM-DD HH:mm:ss.SSS Z'),
  },
  {
    user_id: 4,
    chef_id: 1,
    food: 'Falafel',
    cuisine: 'Mediterranean',
    description: 'Chia seeds is what gives it that out-of-this-world flavor!',
    quantity: 5,
    price: 49.70,
    address: '261 Aspen Court, Lincolnton, NC 28092',
    order_date: '2009-11-25 20:03:28.482',
    rating: 3,
    review: 'It tasted alright, but falafels made from chia seeds??',
    createdAt: moment().format('YYYY-MM-DD HH:mm:ss.SSS Z'),
    updatedAt: moment().format('YYYY-MM-DD HH:mm:ss.SSS Z'),
  },
  {
    user_id: 4,
    chef_id: 3,
    food: 'Hot wings',
    cuisine: 'American',
    description: 'Bell peppers to give it that heat!',
    quantity: 20,
    price: 284.00,
    address: '906 Main Street South, Melrose, MA 02176',
    order_date: '2008-05-30 07:38:24.006',
    rating: 3,
    review: 'I asked for extra-spicy, but it barely broke mild.',
    createdAt: moment().format('YYYY-MM-DD HH:mm:ss.SSS Z'),
    updatedAt: moment().format('YYYY-MM-DD HH:mm:ss.SSS Z'),
  },
  {
    user_id: 1,
    chef_id: 3,
    food: 'Crepe',
    cuisine: 'French',
    description: 'Ooooh laaaaa laaaaa',
    quantity: 2,
    price: 26.53,
    address: '848 Creek Road, Hamden, CT 06514',
    order_date: '2011-09-12 20:47:25.435',
    rating: 5,
    review: 'Nothing like a great home-cooked meal... without cooking it myself!',
    createdAt: moment().format('YYYY-MM-DD HH:mm:ss.SSS Z'),
    updatedAt: moment().format('YYYY-MM-DD HH:mm:ss.SSS Z'),
  },
  {
    user_id: 3,
    chef_id: 1,
    food: 'Sushi',
    cuisine: 'Japanese',
    description: 'The rice is what makes great sushi!!',
    quantity: 500,
    price: 5000.00,
    address: '312 Amherst Street, Smyrna, GA 30080',
    order_date: '2010-02-17 12:59:17.677',
    rating: 4,
    review: 'Expensive, but worth every piece.',
    createdAt: moment().format('YYYY-MM-DD HH:mm:ss.SSS Z'),
    updatedAt: moment().format('YYYY-MM-DD HH:mm:ss.SSS Z'),
  },
];
