module.exports = [
  {
    firstName: 'Andrew',
    lastName: 'Fung',
    email: 'andrew@andrew.com',
    phone: '(812)133-8036',
    password: 'andrewfung',
    address: '229 Evergreen Drive, Bloomington, IN',
    zip: '47401',
    chef: true,
  },
  {
    firstName: 'Shinji',
    lastName: 'Furuya',
    email: 'shinji@shinji.com',
    phone: '(952)288-4204',
    password: 'shinjifuruya',
    address: '306 Street Road, Chaska, MN',
    zip: '55318',
    chef: false,
  },
  {
    firstName: 'Dan',
    lastName: 'Sajjad',
    email: 'dan@dan.com',
    phone: '(630)470-7327',
    password: 'dansajjad',
    address: '575 Winding Way, Streamwood, IL',
    zip: '60107',
    chef: true,
  },
  {
    firstName: 'Alex',
    lastName: 'Wong',
    email: 'alex@alex.com',
    phone: '(609)860-2286',
    password: 'alexwong',
    address: '466 Mechanic Street, Willingboro, NJ',
    zip: '08046',
    chef: false,
  },
];
