module.exports = [
  {
    firstName: 'Andrew',
    lastName: 'Fung',
    email: 'andrew@andrew.com',
    description: 'They call me the Wu-shef; adding plenty of kick to your meals!',
    phone: '(812)133-8036',
    password: 'andrewfung',
    address: '229 Evergreen Drive, Bloomington, IN',
    zip: '47401',
    profile: 'https://avatars3.githubusercontent.com/u/15877600?v=3&s=460',
    chef: true,
  },
  {
    firstName: 'Shinji',
    lastName: 'Furuya',
    email: 'shinji@shinji.com',
    description: '',
    phone: '(952)288-4204',
    password: 'shinjifuruya',
    address: '306 Street Road, Chaska, MN',
    zip: '55318',
    profile: 'https://avatars2.githubusercontent.com/u/12400009?v=3&s=460',
    chef: false,
  },
  {
    firstName: 'Dan',
    lastName: 'Sajjad',
    email: 'dan@dan.com',
    description: 'Conquer Illinois today, dominate the world tomorrow!!!',
    phone: '(630)470-7327',
    password: 'dansajjad',
    address: '575 Winding Way, Streamwood, IL',
    zip: '60107',
    profile: 'https://avatars1.githubusercontent.com/u/13027474?v=3&s=460',
    chef: true,
  },
  {
    firstName: 'Alex',
    lastName: 'Wong',
    email: 'alex@alex.com',
    description: '',
    phone: '(609)860-2286',
    password: 'alexwong',
    address: '466 Mechanic Street, Willingboro, NJ',
    zip: '08046',
    profile: 'https://avatars1.githubusercontent.com/u/17346712?v=3&s=460',
    chef: false,
  },
];
